#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1 on Fri Aug 18 19:30:42 2006

import wx
import numpy as np

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.ScrolledWindow(self, -1, style=wx.TAB_TRAVERSAL)
        self.label_5_copy = wx.StaticText(self.panel_1, -1, "0ms")
        self.label_5_copy_1 = wx.StaticText(self.panel_1, -1, "20ms")
        self.label_5_copy_1_copy = wx.StaticText(self.panel_1, -1, "40ms")
        self.label_5_copy_2 = wx.StaticText(self.panel_1, -1, "n0")
        #self.panel_3 = wx.Panel(self.panel_1, -1)
        im = wx.ImageFromData(2, 1, np.array([255,0,0,0,0,255], dtype=np.uint8).data)
        #self.panel_3 = wx.Panel(self.panel_1, -1)

        self.panel_3 = wx.StaticBitmap(parent=self.panel_1, bitmap=im.ConvertToBitmap())
        self.panel_3_copy_2 = wx.Panel(self.panel_1, -1)
        self.panel_3_copy_7 = wx.Panel(self.panel_1, -1)
        self.label_5_copy_3 = wx.StaticText(self.panel_1, -1, "n1")
        self.panel_3_copy = wx.Panel(self.panel_1, -1)
        self.panel_3_copy_1 = wx.Panel(self.panel_1, -1)
        self.panel_3_copy_6 = wx.Panel(self.panel_1, -1)
        self.label_5_copy_3_copy = wx.StaticText(self.panel_1, -1, "n2")
        self.panel_3_copy_3 = wx.Panel(self.panel_1, -1)
        self.panel_3_copy_4 = wx.Panel(self.panel_1, -1)
        self.panel_3_copy_5 = wx.Panel(self.panel_1, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.SetBackgroundColour(wx.Colour(212, 208, 200))
        #SetMinSize((64,64))
        #self.panel_3.self.panel_3.SetBackgroundColour(wx.Colour(0, 255, 0))
        #self.panel_3.SetForegroundColour(wx.Colour(255, 0, 0))
        self.panel_3_copy_2.SetMinSize((64,64))
        self.panel_3_copy_2.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.panel_3_copy_2.SetForegroundColour(wx.Colour(255, 0, 0))
        self.panel_3_copy_7.SetMinSize((64,64))
        self.panel_3_copy_7.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.panel_3_copy_7.SetForegroundColour(wx.Colour(255, 0, 0))
        self.panel_3_copy.SetMinSize((64,64))
        self.panel_3_copy.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.panel_3_copy.SetForegroundColour(wx.Colour(255, 0, 0))
        self.panel_3_copy_1.SetMinSize((64,64))
        self.panel_3_copy_1.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.panel_3_copy_1.SetForegroundColour(wx.Colour(255, 0, 0))
        self.panel_3_copy_6.SetMinSize((64,64))
        self.panel_3_copy_6.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.panel_3_copy_6.SetForegroundColour(wx.Colour(255, 0, 0))
        self.panel_3_copy_3.SetMinSize((64,64))
        self.panel_3_copy_3.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.panel_3_copy_3.SetForegroundColour(wx.Colour(255, 0, 0))
        self.panel_3_copy_4.SetMinSize((64,64))
        self.panel_3_copy_4.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.panel_3_copy_4.SetForegroundColour(wx.Colour(255, 0, 0))
        self.panel_3_copy_5.SetMinSize((64,64))
        self.panel_3_copy_5.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.panel_3_copy_5.SetForegroundColour(wx.Colour(255, 0, 0))
        self.panel_1.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(4, 4, 2, 2)
        grid_sizer_1.Add((1, 1), 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_5_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_5_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_5_copy_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_5_copy_2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_3_copy_2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_3_copy_7, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_5_copy_3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.panel_3_copy, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_3_copy_1, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_3_copy_6, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_5_copy_3_copy, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.panel_3_copy_3, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_3_copy_4, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_3_copy_5, 1, wx.EXPAND, 0)
        self.panel_1.SetAutoLayout(True)
        self.panel_1.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self.panel_1)
        grid_sizer_1.SetSizeHints(self.panel_1)
        grid_sizer_1.AddGrowableRow(1)
        grid_sizer_1.AddGrowableRow(2)
        grid_sizer_1.AddGrowableRow(3)
        grid_sizer_1.AddGrowableCol(1)
        grid_sizer_1.AddGrowableCol(2)
        grid_sizer_1.AddGrowableCol(3)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND|wx.SHAPED, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
